adminEmail: admin@localhost

image:
  repository: chocobozzz/peertube
  tag: production-stretch
  pullPolicy: IfNotPresent

config:
  signupEnabled: false
  transcodingEnabled: false
  contactFormEnabled: false
  logLevel: debug

webserver:
  hostname: localhost

ingress:
  tls:
    enabled: false

service:
  type: NodePort
  port: 8084 # PeerTube => P T => 80 84

pvc:
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Gi

deps:
  pg:
    managed: true
  redis:
    managed: true
  smtp:
    existingSecret: false
    username: a
    password: a
    hostname: localhost
    port: 25
    from: noreply@localhost
    tls:
      enabled: false
      existingSecret: false
      cert:
      key:

postgresql:
  fullnameOverride: peertube-postgresql-1531009616
  postgresqlDatabase: peertube

redis:
  fullnameOverride: peertube-redis-1531009616
  usePassword: false
  auth:
    enabled: false
  image:
    repository: redis
    tag: 6.2.4
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
