apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "peertube.fullName" . }}
  labels:
    app: {{ template "peertube.fullName" . }}
    chart: {{ template "peertube.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
{{- if .Values.ingress.tls.existingSecret }}
  - secretName: {{ .Values.ingress.tls.existingSecret }}
{{- else }}
  - secretName: {{ template "peertube.tlsIngressSecretName" . }}
{{- end }}
{{- end }}
  defaultBackend:
    service:
      name: {{ template "peertube.fullName" . }}
      port:
        name: ing2svc
